# This is a basic workflow to help you get started with Actions

name: Test The CSV

# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testcsv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
  
      - name: Export Dependabot alerts
        uses: affrae/dependabot-alert-export@main
        with:        
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          org_name: 'octodemo'
          repo_name: 'Fabrikam-Dependabot1'
          csv_path: data/vulnerability.csv
          
      - name: Upload Vulnerability report
        uses: actions/upload-artifact@v3
        with:
           name: vulnerability_report
           path: data/vulnerability.csv        
